CREATE TABLE `registration_otps` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `otp_code` varchar(10) NOT NULL,
  `generated_by` int(11) NOT NULL,
  `target_role` enum('landlord','resident') NOT NULL,
  `house_number` varchar(50) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `house_id` int(11) DEFAULT NULL,
  `expires_at` datetime NOT NULL,
  `used_at` datetime DEFAULT NULL,
  `used_by` int(11) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  `metadata` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `registration_otps_otp_code_unique` (`otp_code`),
  KEY `registration_otps_generated_by_foreign` (`generated_by`),
  KEY `registration_otps_used_by_foreign` (`used_by`),
  KEY `registration_otps_house_id_foreign` (`house_id`),
  KEY `registration_otps_otp_code_is_active_index` (`otp_code`,`is_active`),
  KEY `registration_otps_generated_by_target_role_index` (`generated_by`,`target_role`),
  KEY `registration_otps_expires_at_index` (`expires_at`),
  CONSTRAINT `registration_otps_generated_by_foreign` FOREIGN KEY (`generated_by`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `registration_otps_used_by_foreign` FOREIGN KEY (`used_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `registration_otps_house_id_foreign` FOREIGN KEY (`house_id`) REFERENCES `houses` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;