<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spring Field Estate - Registration OTP</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 8px 8px 0 0;
            margin: -20px -20px 20px -20px;
        }
        .otp-box {
            background: #f8f9fa;
            border: 2px solid #667eea;
            border-radius: 8px;
            text-align: center;
            padding: 20px;
            margin: 20px 0;
        }
        .otp-code {
            font-size: 32px;
            font-weight: bold;
            color: #667eea;
            letter-spacing: 4px;
            margin: 10px 0;
        }
        .info-section {
            background: #e3f2fd;
            border-left: 4px solid #2196f3;
            padding: 15px;
            margin: 20px 0;
        }
        .warning {
            background: #fff3cd;
            border: 1px solid #ffeaa7;
            color: #856404;
            padding: 10px;
            border-radius: 4px;
            margin: 15px 0;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 12px;
            border-top: 1px solid #eee;
            padding-top: 20px;
        }
        .house-info {
            background: #f0f9ff;
            border: 1px solid #0ea5e9;
            border-radius: 6px;
            padding: 15px;
            margin: 15px 0;
        }
        .button {
            display: inline-block;
            background: #667eea;
            color: white;
            padding: 12px 25px;
            text-decoration: none;
            border-radius: 5px;
            margin: 15px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🏠 Spring Field Estate</h1>
            <p>Registration OTP Code</p>
        </div>

        <h2>Hello!</h2>
        
        <p>You have been provided with an OTP code to register as a <strong>{{ ucfirst($targetRole) }}</strong> on Spring Field Estate platform.</p>

        <div class="otp-box">
            <h3>Your Registration OTP Code</h3>
            <div class="otp-code">{{ $otpCode }}</div>
            <p><em>Please use this code to complete your registration</em></p>
        </div>

        @if($houseInfo)
        <div class="house-info">
            <h4>🏡 Pre-filled Property Information</h4>
            <p><strong>House Number:</strong> {{ $houseInfo['house_number'] }}</p>
            <p><strong>Address:</strong> {{ $houseInfo['address'] }}</p>
            <p><em>This information will be automatically filled during registration</em></p>
        </div>
        @endif

        <div class="info-section">
            <h4>📋 Registration Details</h4>
            <ul>
                <li><strong>Role:</strong> {{ ucfirst($targetRole) }}</li>
                <li><strong>Generated by:</strong> {{ $generatedBy }}</li>
                <li><strong>Expires at:</strong> {{ $expiresAt->format('M j, Y \a\t g:i A') }}</li>
                <li><strong>Valid for:</strong> {{ $expiresAt->diffForHumans() }}</li>
            </ul>
        </div>

        <div class="warning">
            <strong>⚠️ Important:</strong>
            <ul style="margin: 5px 0; padding-left: 20px;">
                <li>This OTP code is valid for <strong>one-time use only</strong></li>
                <li>Do not share this code with anyone</li>
                <li>Code expires on {{ $expiresAt->format('M j, Y \a\t g:i A') }}</li>
                <li>Contact your administrator if you need assistance</li>
            </ul>
        </div>

        <div style="text-align: center;">
            <a href="{{ config('app.url') }}" class="button">
                Start Registration
            </a>
        </div>

        <div class="footer">
            <p>This email was sent by Spring Field Estate Management System</p>
            <p>If you did not request this OTP code, please contact your administrator immediately.</p>
            <p>&copy; {{ date('Y') }} Spring Field Estate. All rights reserved.</p>
        </div>
    </div>
</body>
</html>