Spring Field Estate - Registration OTP Code

Hello!

You have been provided with an OTP code to register as a {{ ucfirst($targetRole) }} on Spring Field Estate platform.

YOUR REGISTRATION OTP CODE: {{ $otpCode }}

@if($houseInfo)
Pre-filled Property Information:
- House Number: {{ $houseInfo['house_number'] }}
- Address: {{ $houseInfo['address'] }}
(This information will be automatically filled during registration)
@endif

Registration Details:
- Role: {{ ucfirst($targetRole) }}
- Generated by: {{ $generatedBy }}
- Expires at: {{ $expiresAt->format('M j, Y \a\t g:i A') }}
- Valid for: {{ $expiresAt->diffForHumans() }}

IMPORTANT:
- This OTP code is valid for ONE-TIME USE ONLY
- Do not share this code with anyone
- Code expires on {{ $expiresAt->format('M j, Y \a\t g:i A') }}
- Contact your administrator if you need assistance

Start Registration: {{ config('app.url') }}

---
This email was sent by Spring Field Estate Management System
If you did not request this OTP code, please contact your administrator immediately.

© {{ date('Y') }} Spring Field Estate. All rights reserved.